language: php
php:
  - 5.5
  - 5.6
  - 7.0

addons:
  code_climate:
    repo_token: 4f0b1117a1a8f9e880d4878ff4ee2be0066baaad59a6d18f68ba449898265fc7

install:
  - composer install

before_script:
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit

after_script:
  - ./vendor/bin/test-reporter

