language: php
php:
  - 5.5
  - 5.6

install:
  - composer self-update
  - composer install -n

before_script:
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml

after_script:
  - then php vendor/bin/ocular code-coverage:upload --format=php-clover ./build/logs/clover.xml
